// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use super::schema::*;
use chrono::NaiveDateTime;

#[derive(Queryable, Debug, Identifiable)]
#[table_name = "authors"]
pub struct Author {
    pub id: i32,
    pub name: String,
}

#[derive(Queryable, Debug, Identifiable)]
#[table_name = "categories"]
pub struct Category {
    pub id: i32,
    pub name: String,
}

#[derive(Queryable, Debug, Identifiable)]
#[primary_key(paper_id, author_id)]
#[table_name = "paper_authors"]
pub struct PaperAuthor {
    pub paper_id: i32,
    pub author_id: i32,
}

#[derive(Queryable, Debug, Identifiable)]
#[table_name = "papers"]
pub struct Paper {
    pub id: i32,
    pub title: String,
    pub url: String,
    pub pdf_url: String,
    pub category_id: i32,
    pub summary: String,
    pub comment: String,
    pub accepted: i32,
    pub updated: NaiveDateTime,
    pub published: NaiveDateTime,
    pub created: NaiveDateTime,
}

#[derive(Queryable, Debug, Identifiable)]
#[table_name = "slack_notifications"]
pub struct SlackNotification {
    pub id: i32,
    pub paper_id: i32,
    pub slack_url: String,
    pub updated_at: NaiveDateTime,
    pub send: bool,
    pub created: NaiveDateTime,
}

